# Generated by Django 3.2.24 on 2024-03-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infer', '0002_infer_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
